/* This software is published under the BSD license                          */
/* as listed below.                                                          */
/*                                                                           */
/* Copyright (c) 2004-2016, CRIXP Corp., Switzerland                         */
/* All rights reserved.                                                      */
/*                                                                           */
/* Redistribution and use in source and binary forms, with or without        */
/* modification, are permitted provided that the following conditions        */
/* are met:                                                                  */
/*                                                                           */
/* * Redistributions of source code must retain the above copyright          */
/* notice, this list of conditions and the following disclaimer.             */
/*                                                                           */
/* * Redistributions in binary form must reproduce the above copyright       */
/* notice, this list of conditions and the following disclaimer in           */
/* the documentation and/or other materials provided with the                */
/* distribution.                                                             */
/*                                                                           */
/* * Neither the name of CRIXP Corp. nor the names of the contributors       */
/* to openCRX may be used to endorse or promote products derived             */
/* from this software without specific prior written permission              */
/*                                                                           */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND                    */
/* CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,               */
/* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF                  */
/* MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE                  */
/* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS         */
/* BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,                  */
/* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED           */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,             */
/* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON         */
/* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,           */
/* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY            */
/* OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE                   */
/* POSSIBILITY OF SUCH DAMAGE.                                               */
/*                                                                           */
/* ------------------                                                        */
/*                                                                           */
/* This product includes software developed by the Apache Software           */
/* Foundation (http://www.apache.org/).                                      */
/*                                                                           */
/* This product includes software developed by contributors to               */
/* openMDX (http://www.openmdx.org/)                                         */
/*                                                                           */

ALTER TABLE OOCKE1_PRODUCT ADD COLUMN DEPOT_ASSIGNMENT_GROUP VARCHAR(256);
CREATE TABLE OOCKE1_DEPOTASSIGNMENTGROUP (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, CATEGORY_ INTEGER DEFAULT -1, COST_CENTER VARCHAR(256), CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), DISABLED BOOLEAN, DISABLED_REASON VARCHAR(256), EXTERNAL_LINK_ INTEGER DEFAULT -1, INCOME_ACCOUNT VARCHAR(256), MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, SALES_TAX_TYPE_GROUP VARCHAR(256), SALES_TRANSACTION_TYPE VARCHAR(256), "P$$PARENT" VARCHAR(256), USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_DEPOTASSIGNMENTGROUP_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CATEGORY VARCHAR(256), CREATED_BY VARCHAR(256), EXTERNAL_LINK VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));


ALTER TABLE OOCKE1_ACCOUNT ADD COLUMN SEARCH_NAME VARCHAR(256);


ALTER TABLE OOCKE1_CONTRACT ADD COLUMN SALES_TAX_TYPE_GROUP VARCHAR(256);
ALTER TABLE OOCKE1_CONTRACTCREATOR ADD COLUMN SALES_TAX_TYPE_GROUP VARCHAR(256);
ALTER TABLE OOCKE1_CONTRACTPOSITION ADD COLUMN SALES_TRANSACTION_TYPE VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN CATEGORY_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN DISABLED BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN DISABLED_REASON VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN EXTERNAL_LINK_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_BOOLEAN0 BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_BOOLEAN1 BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_BOOLEAN2 BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_BOOLEAN3 BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_BOOLEAN4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_CODE0 SMALLINT;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_CODE1 SMALLINT;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_CODE2 SMALLINT;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_CODE3 SMALLINT;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_CODE4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_DATE0 DATE;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_DATE1 DATE;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_DATE2 DATE;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_DATE3 DATE;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_DATE4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_DATE_TIME0 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_DATE_TIME1 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_DATE_TIME2 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_DATE_TIME3 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_DATE_TIME4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_NUMBER0 NUMERIC(19,9);
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_NUMBER1 NUMERIC(19,9);
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_NUMBER2 NUMERIC(19,9);
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_NUMBER3 NUMERIC(19,9);
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_NUMBER4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_STRING0 VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_STRING1 VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_STRING2 VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_STRING3 VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN USER_STRING4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREFERENCE ADD COLUMN DEPOT_POSITION VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREFERENCE_ ADD COLUMN CATEGORY VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREFERENCE_ ADD COLUMN EXTERNAL_LINK VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREFERENCE_ ADD COLUMN USER_BOOLEAN4 BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREFERENCE_ ADD COLUMN USER_CODE4 SMALLINT;
ALTER TABLE OOCKE1_DEPOTREFERENCE_ ADD COLUMN USER_DATE4 DATE;
ALTER TABLE OOCKE1_DEPOTREFERENCE_ ADD COLUMN USER_DATE_TIME4 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREFERENCE_ ADD COLUMN USER_NUMBER4 NUMERIC(19,9);
ALTER TABLE OOCKE1_DEPOTREFERENCE_ ADD COLUMN USER_STRING4 VARCHAR(256);
ALTER TABLE OOCKE1_SALESTAXTYPE ADD COLUMN SALES_TAX_TYPE_GROUP VARCHAR(256);
ALTER TABLE OOCKE1_SALESTAXTYPE ADD COLUMN SALES_TRANSACTION_TYPE_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_SALESTAXTYPE_ ADD COLUMN SALES_TRANSACTION_TYPE VARCHAR(256);
CREATE TABLE OOCKE1_SALESTAXTYPEASSIGNMENT (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, CATEGORY_ INTEGER DEFAULT -1, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), DISABLED BOOLEAN, DISABLED_REASON VARCHAR(256), EXTERNAL_LINK_ INTEGER DEFAULT -1, MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, "P$$PARENT" VARCHAR(256), SALES_TAX_TYPE VARCHAR(256), UOM VARCHAR(256), USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_SALESTAXTYPEASSIGNMENT_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CATEGORY VARCHAR(256), CREATED_BY VARCHAR(256), EXTERNAL_LINK VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));
CREATE TABLE OOCKE1_SALESTAXTYPEGROUP (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, CATEGORY_ INTEGER DEFAULT -1, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), DISABLED BOOLEAN, DISABLED_REASON VARCHAR(256), EXTERNAL_LINK_ INTEGER DEFAULT -1, MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, "P$$PARENT" VARCHAR(256), TAX_AUTHORITY VARCHAR(256), TAX_AUTHORITY_COUNTRY SMALLINT, TAX_AUTHORITY_POSTAL_CODE VARCHAR(256), USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_SALESTAXTYPEGROUP_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CATEGORY VARCHAR(256), CREATED_BY VARCHAR(256), EXTERNAL_LINK VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));
CREATE TABLE OOCKE1_SALESTRANSACTIONTYPE (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, CATEGORY_ INTEGER DEFAULT -1, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), DISABLED BOOLEAN, DISABLED_REASON VARCHAR(256), EXTERNAL_LINK_ INTEGER DEFAULT -1, MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, "P$$PARENT" VARCHAR(256), USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_SALESTRANSACTIONTYPE_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CATEGORY VARCHAR(256), CREATED_BY VARCHAR(256), EXTERNAL_LINK VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));



ALTER TABLE OOCKE1_ACCOUNT ADD COLUMN ORIGINAL_NAME VARCHAR(256);
ALTER TABLE OOCKE1_SALESTAXTYPE ADD COLUMN PARENT_SALES_TAX_TYPE VARCHAR(256);
ALTER TABLE OOCKE1_SALESTAXTYPE ADD COLUMN SHORT_NAME VARCHAR(256);
ALTER TABLE OOCKE1_SALESTAXTYPE ADD COLUMN TAX_AUTHORITY VARCHAR(256);
ALTER TABLE OOCKE1_SALESTAXTYPE ADD COLUMN VALID_FROM TIMESTAMP;
ALTER TABLE OOCKE1_SALESTAXTYPE ADD COLUMN VALID_TO TIMESTAMP;
CREATE TABLE OOCKE1_FXRATE (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, CATEGORY_ INTEGER DEFAULT -1, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, CURRENCY_BUY SMALLINT, CURRENCY_SELL SMALLINT, DESCRIPTION VARCHAR(256), DISABLED BOOLEAN, DISABLED_REASON VARCHAR(256), EXTERNAL_LINK_ INTEGER DEFAULT -1, FX_RATE_PROVIDER VARCHAR(256), FX_RATE_TYPE SMALLINT, MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, RATE NUMERIC(19,9), "P$$PARENT" VARCHAR(256), TRANSACTION_SIZE_FROM NUMERIC(19,9), TRANSACTION_SIZE_TO NUMERIC(19,9), USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, VALUE_DATE TIMESTAMP, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_FXRATE_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CATEGORY VARCHAR(256), CREATED_BY VARCHAR(256), EXTERNAL_LINK VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));


ALTER TABLE OOCKE1_ACCESSHISTORY ADD COLUMN ACCESS_HISTORY_STATUS SMALLINT;
ALTER TABLE OOCKE1_ACCESSHISTORY ADD COLUMN REFERENCED_OBJECT_TYPE VARCHAR(256);
ALTER TABLE OOCKE1_ALERT ADD COLUMN REFERENCED_OBJECT_TYPE VARCHAR(256);
ALTER TABLE OOCKE1_QUICKACCESS ADD COLUMN QUICK_ACCESS_STATUS SMALLINT;
ALTER TABLE OOCKE1_QUICKACCESS ADD COLUMN REFERENCED_OBJECT_TYPE VARCHAR(256);


ALTER TABLE OOCKE1_ACCOUNTASSIGNMENT ADD COLUMN MEMBER_GROUP_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_ACCOUNTASSIGNMENT_ ADD COLUMN MEMBER_GROUP VARCHAR(256);
ALTER TABLE OOCKE1_ACTIVITYPARTY ADD COLUMN ACTIVITY_PARTY_GROUP_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_ACTIVITYPARTY_ ADD COLUMN ACTIVITY_PARTY_GROUP VARCHAR(256);
CREATE TABLE OOCKE1_ACCOUNTMEMBERGROUP (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, "P$$PARENT" VARCHAR(256), CATEGORY_ INTEGER DEFAULT -1, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), DISABLED BOOLEAN, DISABLED_REASON VARCHAR(256), EXTERNAL_LINK_ INTEGER DEFAULT -1, MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_ACCOUNTMEMBERGROUP_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CATEGORY VARCHAR(256), CREATED_BY VARCHAR(256), EXTERNAL_LINK VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));
CREATE TABLE OOCKE1_ACTIVITYPARTYGROUP (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, "P$$PARENT" VARCHAR(256), CATEGORY_ INTEGER DEFAULT -1, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), DISABLED BOOLEAN, DISABLED_REASON VARCHAR(256), EXTERNAL_LINK_ INTEGER DEFAULT -1, MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_ACTIVITYPARTYGROUP_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CATEGORY VARCHAR(256), CREATED_BY VARCHAR(256), EXTERNAL_LINK VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));


ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_BOOLEAN0 BOOLEAN;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_BOOLEAN1 BOOLEAN;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_BOOLEAN2 BOOLEAN;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_BOOLEAN3 BOOLEAN;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_BOOLEAN4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_CODE0 SMALLINT;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_CODE1 SMALLINT;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_CODE2 SMALLINT;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_CODE3 SMALLINT;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_CODE4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_DATE0 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_DATE1 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_DATE2 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_DATE3 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_DATE4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_DATE_TIME0 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_DATE_TIME1 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_DATE_TIME2 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_DATE_TIME3 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_DATE_TIME4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_NUMBER0 NUMERIC(19,9);
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_NUMBER1 NUMERIC(19,9);
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_NUMBER2 NUMERIC(19,9);
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_NUMBER3 NUMERIC(19,9);
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_NUMBER4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_STRING0 VARCHAR(256);
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_STRING1 VARCHAR(256);
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_STRING2 VARCHAR(256);
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_STRING3 VARCHAR(256);
ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN USER_STRING4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_BOOLEAN0 BOOLEAN;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_BOOLEAN1 BOOLEAN;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_BOOLEAN2 BOOLEAN;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_BOOLEAN3 BOOLEAN;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_BOOLEAN4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_CODE0 SMALLINT;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_CODE1 SMALLINT;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_CODE2 SMALLINT;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_CODE3 SMALLINT;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_CODE4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_DATE0 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_DATE1 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_DATE2 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_DATE3 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_DATE4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_DATE_TIME0 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_DATE_TIME1 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_DATE_TIME2 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_DATE_TIME3 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_DATE_TIME4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_NUMBER0 NUMERIC(19,9);
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_NUMBER1 NUMERIC(19,9);
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_NUMBER2 NUMERIC(19,9);
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_NUMBER3 NUMERIC(19,9);
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_NUMBER4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_STRING0 VARCHAR(256);
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_STRING1 VARCHAR(256);
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_STRING2 VARCHAR(256);
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_STRING3 VARCHAR(256);
ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD COLUMN USER_STRING4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DOCUMENTFOLDER_ ADD COLUMN USER_BOOLEAN4 BOOLEAN;
ALTER TABLE OOCKE1_DOCUMENTFOLDER_ ADD COLUMN USER_CODE4 SMALLINT;
ALTER TABLE OOCKE1_DOCUMENTFOLDER_ ADD COLUMN USER_DATE4 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENTFOLDER_ ADD COLUMN USER_DATE_TIME4 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENTFOLDER_ ADD COLUMN USER_NUMBER4 NUMERIC(19,9);
ALTER TABLE OOCKE1_DOCUMENTFOLDER_ ADD COLUMN USER_STRING4 VARCHAR(256);
ALTER TABLE OOCKE1_DOCUMENT_ ADD COLUMN USER_BOOLEAN4 BOOLEAN;
ALTER TABLE OOCKE1_DOCUMENT_ ADD COLUMN USER_CODE4 SMALLINT;
ALTER TABLE OOCKE1_DOCUMENT_ ADD COLUMN USER_DATE4 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENT_ ADD COLUMN USER_DATE_TIME4 TIMESTAMP;
ALTER TABLE OOCKE1_DOCUMENT_ ADD COLUMN USER_NUMBER4 NUMERIC(19,9);
ALTER TABLE OOCKE1_DOCUMENT_ ADD COLUMN USER_STRING4 VARCHAR(256);


ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_BOOLEAN0 BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_BOOLEAN1 BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_BOOLEAN2 BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_BOOLEAN3 BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_BOOLEAN4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_CODE0 SMALLINT;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_CODE1 SMALLINT;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_CODE2 SMALLINT;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_CODE3 SMALLINT;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_CODE4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_DATE0 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_DATE1 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_DATE2 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_DATE3 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_DATE4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_DATE_TIME0 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_DATE_TIME1 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_DATE_TIME2 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_DATE_TIME3 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_DATE_TIME4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_NUMBER0 NUMERIC(19,9);
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_NUMBER1 NUMERIC(19,9);
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_NUMBER2 NUMERIC(19,9);
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_NUMBER3 NUMERIC(19,9);
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_NUMBER4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_STRING0 VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_STRING1 VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_STRING2 VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_STRING3 VARCHAR(256);
ALTER TABLE OOCKE1_DEPOTREPORTITEM ADD COLUMN USER_STRING4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_DEPOTREPORTITEM_ ADD COLUMN USER_BOOLEAN4 BOOLEAN;
ALTER TABLE OOCKE1_DEPOTREPORTITEM_ ADD COLUMN USER_CODE4 SMALLINT;
ALTER TABLE OOCKE1_DEPOTREPORTITEM_ ADD COLUMN USER_DATE4 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREPORTITEM_ ADD COLUMN USER_DATE_TIME4 TIMESTAMP;
ALTER TABLE OOCKE1_DEPOTREPORTITEM_ ADD COLUMN USER_NUMBER4 NUMERIC(19,9);
ALTER TABLE OOCKE1_DEPOTREPORTITEM_ ADD COLUMN USER_STRING4 VARCHAR(256);


ALTER TABLE OOCKE1_BOOKINGTEMPLATE ADD COLUMN DISABLED BOOLEAN;
ALTER TABLE OOCKE1_BOOKINGTEMPLATE ADD COLUMN DISABLED_REASON VARCHAR(256);


ALTER TABLE OOCKE1_DEPOTPOSITION ADD COLUMN INITIAL_BALANCE NUMERIC(19,9);
ALTER TABLE OOCKE1_INVENTORYLEVEL ADD COLUMN CORRECTION_BOOKING_TEMPLATE VARCHAR(256);
CREATE TABLE OOCKE1_BOOKINGTEMPLATE (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, BOOKING_TEXT VARCHAR(256), BOOKING_TEXT_SUFFIX VARCHAR(256), BOOKING_TYPE SMALLINT, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, "P$$PARENT" VARCHAR(256), DESCRIPTION VARCHAR(256), MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, POSITION_CREDIT VARCHAR(256), POSITION_DEBIT VARCHAR(256), USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_BOOKINGTEMPLATE_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CREATED_BY VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));


ALTER TABLE OOCKE1_CONTACTMEMBERSHIP ADD COLUMN DESCRIPTION VARCHAR(256);
ALTER TABLE OOCKE1_CONTACTMEMBERSHIP ADD COLUMN NAME VARCHAR(256);


ALTER TABLE OOCKE1_INVENTORYLEVEL ADD COLUMN ACCEPTED_BY_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_INVENTORYLEVEL ADD COLUMN LOCK_MODIFIED_AT TIMESTAMP;
ALTER TABLE OOCKE1_INVENTORYLEVEL ADD COLUMN IS_LOCKED BOOLEAN;
ALTER TABLE OOCKE1_INVENTORYLEVEL ADD COLUMN LOCKING_REASON SMALLINT;
ALTER TABLE OOCKE1_INVENTORYLEVEL_ ADD COLUMN ACCEPTED_BY VARCHAR(256);


ALTER TABLE OOCKE1_DOCUMENT ADD COLUMN DOCUMENT_SCHEMA VARCHAR(256);
CREATE TABLE OOCKE1_DOCUMENTSCHEMA (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, SCHEMA_TEXT CLOB(10000000), SCHEMA_TYPE VARCHAR(256), "P$$PARENT" VARCHAR(256), DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_DOCUMENTSCHEMA_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CREATED_BY VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));
CREATE TABLE OOCKE1_INVENTORYLEVEL (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, CATEGORY_ INTEGER DEFAULT -1, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), DISABLED BOOLEAN, DISABLED_REASON VARCHAR(256), ENTRY_DATE TIMESTAMP, EXTERNAL_LINK_ INTEGER DEFAULT -1, INVENTORY_LEVEL_STATUS SMALLINT, INVENTORY_LEVEL_TYPE SMALLINT, MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), ORIGIN_CONTEXT VARCHAR(256), ORIGIN_CONTEXT_PARAMS_ INTEGER DEFAULT -1, ORIGIN_ID VARCHAR(256), OWNER_ INTEGER DEFAULT -1, POSITION VARCHAR(256), QUANTITY NUMERIC(19,9), "P$$PARENT" VARCHAR(256), USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, VALUE_DATE TIMESTAMP, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_INVENTORYLEVEL_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CATEGORY VARCHAR(256), CREATED_BY VARCHAR(256), EXTERNAL_LINK VARCHAR(256), MODIFIED_BY VARCHAR(256), ORIGIN_CONTEXT_PARAMS VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));


ALTER TABLE OOCKE1_WFPROCESS ADD COLUMN FOR_CLASS_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_WFPROCESS_ ADD COLUMN FOR_CLASS VARCHAR(256);
