/* This software is published under the BSD license                          */
/* as listed below.                                                          */
/*                                                                           */
/* Copyright (c) 2004-2019, CRIXP Corp., Switzerland                         */
/* All rights reserved.                                                      */
/*                                                                           */
/* Redistribution and use in source and binary forms, with or without        */
/* modification, are permitted provided that the following conditions        */
/* are met:                                                                  */
/*                                                                           */
/* * Redistributions of source code must retain the above copyright          */
/* notice, this list of conditions and the following disclaimer.             */
/*                                                                           */
/* * Redistributions in binary form must reproduce the above copyright       */
/* notice, this list of conditions and the following disclaimer in           */
/* the documentation and/or other materials provided with the                */
/* distribution.                                                             */
/*                                                                           */
/* * Neither the name of CRIXP Corp. nor the names of the contributors       */
/* to openCRX may be used to endorse or promote products derived             */
/* from this software without specific prior written permission              */
/*                                                                           */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND                    */
/* CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,               */
/* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF                  */
/* MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE                  */
/* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS         */
/* BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,                  */
/* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED           */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,             */
/* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON         */
/* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,           */
/* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY            */
/* OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE                   */
/* POSSIBILITY OF SUCH DAMAGE.                                               */
/*                                                                           */
/* ------------------                                                        */
/*                                                                           */
/* This product includes software developed by the Apache Software           */
/* Foundation (http://www.apache.org/).                                      */
/*                                                                           */
/* This product includes software developed by contributors to               */
/* openMDX (http://www.openmdx.org/)                                         */
/*                                                                           */

ALTER TABLE OOCKE1_SIMPLEBOOKING ADD COLUMN IS_LOCKED BOOLEAN;
ALTER TABLE OOCKE1_SIMPLEBOOKING ADD COLUMN LOCK_MODIFIED_AT TIMESTAMP;
ALTER TABLE OOCKE1_SIMPLEBOOKING ADD COLUMN LOCKING_REASON SMALLINT;


ALTER TABLE OOCKE1_CONTRACTPOSITION ADD COLUMN DISCOUNT_CALCULATION_TYPE SMALLINT;
ALTER TABLE OOCKE1_CONTRACTPOSITION ADD COLUMN DISCOUNT_ORIGIN VARCHAR(256);
ALTER TABLE OOCKE1_CONTRACTPOSITION ADD COLUMN MANUAL_PRICING BOOLEAN;
ALTER TABLE OOCKE1_PRICELEVEL ADD COLUMN DISCOUNT_SCHEDULE VARCHAR(256);
CREATE TABLE OOCKE1_DISCOUNTRULE (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, CATEGORY_ INTEGER DEFAULT -1, CONDITION VARCHAR(256), CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), DISABLED BOOLEAN, DISABLED_REASON VARCHAR(256), DISCOUNT NUMERIC(19,9), DISCOUNT_IS_PERCENTAGE BOOLEAN, "P$$PARENT" VARCHAR(256), EXTERNAL_LINK_ INTEGER DEFAULT -1, MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, SEARCH_DATE_TIME0 TIMESTAMP, SEARCH_DATE_TIME1 TIMESTAMP, SEARCH_DATE_TIME2 TIMESTAMP, SEARCH_DATE_TIME3 TIMESTAMP, SEARCH_DATE_TIME4 TIMESTAMP, SEARCH_DATE_TIME5 TIMESTAMP, SEARCH_DATE_TIME6 TIMESTAMP, SEARCH_DATE_TIME7 TIMESTAMP, SEARCH_DATE_TIME8 TIMESTAMP, SEARCH_DATE_TIME9 TIMESTAMP, SEARCH_NUMBER0 NUMERIC(19,9), SEARCH_NUMBER1 NUMERIC(19,9), SEARCH_NUMBER2 NUMERIC(19,9), SEARCH_NUMBER3 NUMERIC(19,9), SEARCH_NUMBER4 NUMERIC(19,9), SEARCH_NUMBER5 NUMERIC(19,9), SEARCH_NUMBER6 NUMERIC(19,9), SEARCH_NUMBER7 NUMERIC(19,9), SEARCH_NUMBER8 NUMERIC(19,9), SEARCH_NUMBER9 NUMERIC(19,9), SEARCH_STRING0 VARCHAR(256), SEARCH_STRING1 VARCHAR(256), SEARCH_STRING2 VARCHAR(256), SEARCH_STRING3 VARCHAR(256), SEARCH_STRING4 VARCHAR(256), SEARCH_STRING5 VARCHAR(256), SEARCH_STRING6 VARCHAR(256), SEARCH_STRING7 VARCHAR(256), SEARCH_STRING8 VARCHAR(256), SEARCH_STRING9 VARCHAR(256), USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_DISCOUNTRULE_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CATEGORY VARCHAR(256), CREATED_BY VARCHAR(256), EXTERNAL_LINK VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));
CREATE TABLE OOCKE1_DISCOUNTSCHEDULE (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, CATEGORY_ INTEGER DEFAULT -1, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), DISABLED BOOLEAN, DISABLED_REASON VARCHAR(256), EXTERNAL_LINK_ INTEGER DEFAULT -1, MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, SEARCH_DATE_TIME0 TIMESTAMP, SEARCH_DATE_TIME1 TIMESTAMP, SEARCH_DATE_TIME2 TIMESTAMP, SEARCH_DATE_TIME3 TIMESTAMP, SEARCH_DATE_TIME4 TIMESTAMP, SEARCH_DATE_TIME5 TIMESTAMP, SEARCH_DATE_TIME6 TIMESTAMP, SEARCH_DATE_TIME7 TIMESTAMP, SEARCH_DATE_TIME8 TIMESTAMP, SEARCH_DATE_TIME9 TIMESTAMP, SEARCH_NUMBER0 NUMERIC(19,9), SEARCH_NUMBER1 NUMERIC(19,9), SEARCH_NUMBER2 NUMERIC(19,9), SEARCH_NUMBER3 NUMERIC(19,9), SEARCH_NUMBER4 NUMERIC(19,9), SEARCH_NUMBER5 NUMERIC(19,9), SEARCH_NUMBER6 NUMERIC(19,9), SEARCH_NUMBER7 NUMERIC(19,9), SEARCH_NUMBER8 NUMERIC(19,9), SEARCH_NUMBER9 NUMERIC(19,9), SEARCH_STRING0 VARCHAR(256), SEARCH_STRING1 VARCHAR(256), SEARCH_STRING2 VARCHAR(256), SEARCH_STRING3 VARCHAR(256), SEARCH_STRING4 VARCHAR(256), SEARCH_STRING5 VARCHAR(256), SEARCH_STRING6 VARCHAR(256), SEARCH_STRING7 VARCHAR(256), SEARCH_STRING8 VARCHAR(256), SEARCH_STRING9 VARCHAR(256), "P$$PARENT" VARCHAR(256), USER_BOOLEAN0 BOOLEAN, USER_BOOLEAN1 BOOLEAN, USER_BOOLEAN2 BOOLEAN, USER_BOOLEAN3 BOOLEAN, USER_BOOLEAN4_ INTEGER DEFAULT -1, USER_CODE0 SMALLINT, USER_CODE1 SMALLINT, USER_CODE2 SMALLINT, USER_CODE3 SMALLINT, USER_CODE4_ INTEGER DEFAULT -1, USER_DATE0 DATE, USER_DATE1 DATE, USER_DATE2 DATE, USER_DATE3 DATE, USER_DATE4_ INTEGER DEFAULT -1, USER_DATE_TIME0 TIMESTAMP, USER_DATE_TIME1 TIMESTAMP, USER_DATE_TIME2 TIMESTAMP, USER_DATE_TIME3 TIMESTAMP, USER_DATE_TIME4_ INTEGER DEFAULT -1, USER_NUMBER0 NUMERIC(19,9), USER_NUMBER1 NUMERIC(19,9), USER_NUMBER2 NUMERIC(19,9), USER_NUMBER3 NUMERIC(19,9), USER_NUMBER4_ INTEGER DEFAULT -1, USER_STRING0 VARCHAR(256), USER_STRING1 VARCHAR(256), USER_STRING2 VARCHAR(256), USER_STRING3 VARCHAR(256), USER_STRING4_ INTEGER DEFAULT -1, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_DISCOUNTSCHEDULE_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CATEGORY VARCHAR(256), CREATED_BY VARCHAR(256), EXTERNAL_LINK VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), USER_BOOLEAN4 BOOLEAN, USER_CODE4 SMALLINT, USER_DATE4 DATE, USER_DATE_TIME4 TIMESTAMP, USER_NUMBER4 NUMERIC(19,9), USER_STRING4 VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));


ALTER TABLE OOCKE1_PRICEMODIFIER ADD COLUMN CLASSIFICATION_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_PRICEMODIFIER ADD COLUMN NAME VARCHAR(256);
ALTER TABLE OOCKE1_PRICEMODIFIER ADD COLUMN ORDER_INDEX INTEGER;
ALTER TABLE OOCKE1_PRICEMODIFIER ADD COLUMN PRICE_MODIFIER VARCHAR(256);
ALTER TABLE OOCKE1_PRICEMODIFIER_ ADD COLUMN CLASSIFICATION VARCHAR(256);


ALTER TABLE OOCKE1_HASHENTRY ADD COLUMN HASH_VALUE_MODIFIED_AT TIMESTAMP;


CREATE TABLE OOCKE1_HASHENTRY (OBJECT_ID VARCHAR(250) NOT NULL, ACCESS_LEVEL_BROWSE SMALLINT, ACCESS_LEVEL_DELETE SMALLINT, ACCESS_LEVEL_UPDATE SMALLINT, CREATED_AT TIMESTAMP, CREATED_BY_ INTEGER DEFAULT -1, DESCRIPTION VARCHAR(256), HASH_VALUE VARCHAR(256), "P$$PARENT" VARCHAR(256), MODIFIED_BY_ INTEGER DEFAULT -1, NAME VARCHAR(256), OWNER_ INTEGER DEFAULT -1, DTYPE VARCHAR(256), MODIFIED_AT TIMESTAMP, PRIMARY KEY (OBJECT_ID));
CREATE TABLE OOCKE1_HASHENTRY_ (OBJECT_ID VARCHAR(250) NOT NULL, IDX INTEGER NOT NULL, CREATED_BY VARCHAR(256), MODIFIED_BY VARCHAR(256), OWNER VARCHAR(256), DTYPE VARCHAR(256), PRIMARY KEY (OBJECT_ID, IDX));


ALTER TABLE OOCKE1_ACCOUNTASSIGNMENT ADD COLUMN MEMBER_CATEGORY VARCHAR(256);
ALTER TABLE OOCKE1_ACTIVITYPARTY ADD COLUMN PARTY_CATEGORY VARCHAR(256);


ALTER TABLE OOCKE1_ACTIVITY ADD COLUMN RECURRENCE_RULE VARCHAR(256);
ALTER TABLE OOCKE1_ACTIVITYPARTY ADD COLUMN REGISTERED_AT TIMESTAMP;
